package migrations_test

import (
	"context"
	"database/sql"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/golang-migrate/migrate/v4"
	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
)

func TestPrivateTeamMigrationPreservesDataAndGuardsRollback(t *testing.T) {
	url := os.Getenv("DATABASE_URL")
	if url == "" {
		t.Skip("DATABASE_URL is not configured")
	}
	admin, err := sql.Open("pgx", url)
	require.NoError(t, err)
	name := "kuayle_privacy_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	_, err = admin.Exec(`CREATE DATABASE "` + name + `"`)
	if postgresCode(err) == "42501" {
		_ = admin.Close()
		t.Skip("DATABASE_URL user cannot create an isolated migration database")
	}
	require.NoError(t, err)
	t.Cleanup(func() {
		_, _ = admin.ExecContext(context.Background(), `DROP DATABASE "`+name+`" WITH (FORCE)`)
		_ = admin.Close()
	})
	testURL := databaseURLWithName(t, url, name)
	m, err := migrate.New("file://.", testURL)
	require.NoError(t, err)
	t.Cleanup(func() { _, _ = m.Close() })
	require.NoError(t, m.Migrate(38))
	db, err := sql.Open("pgx", testURL)
	require.NoError(t, err)
	t.Cleanup(func() { _ = db.Close() })
	fixture := insertBaseMigrationFixture(t, db)
	_, err = db.Exec(`INSERT INTO team_members(team_id,user_id) VALUES($1,$2)`, fixture.teamA, fixture.userA)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO projects(workspace_id,name) VALUES($1,'Existing teamless project')`, fixture.workspaceA)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO notifications(user_id,workspace_id,issue_id,type,title) VALUES($1,$2,$3,'assigned','old linked title')`, fixture.userA, fixture.workspaceA, fixture.issueA)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO notifications(user_id,workspace_id,type,title) VALUES($1,$2,'issue_deleted','old detached title')`, fixture.userA, fixture.workspaceA)
	require.NoError(t, err)
	linkedAsset, ambiguousAsset, orphanAsset := uuid.New(), uuid.New(), uuid.New()
	for _, asset := range []uuid.UUID{linkedAsset, ambiguousAsset, orphanAsset} {
		_, err = db.Exec(`INSERT INTO assets(id,workspace_id,storage_key,filename,content_type,size,uploaded_by) VALUES($1,$2,$3,'old.png','image/png',12,$4)`, asset, fixture.workspaceA, asset.String(), fixture.userA)
		require.NoError(t, err)
	}
	_, err = db.Exec(`UPDATE issues SET description=$1 WHERE id=$2`, "/api/workspaces/old/assets/"+linkedAsset.String()+" /api/workspaces/old/assets/"+ambiguousAsset.String(), fixture.issueA)
	require.NoError(t, err)
	_, err = db.Exec(`UPDATE projects SET description=$1 WHERE workspace_id=$2 AND team_id IS NULL`, "/api/workspaces/old/assets/"+ambiguousAsset.String(), fixture.workspaceA)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO comments(issue_id,user_id,body) VALUES($1,$2,$3)`, fixture.issueA, fixture.userA, "/assets/"+linkedAsset.String())
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO issue_history(issue_id,user_id,field,old_value,new_value) VALUES($1,$2,'description',$3,'updated')`, fixture.issueA, fixture.userA, "/assets/"+linkedAsset.String())
	require.NoError(t, err)
	require.NoError(t, m.Migrate(46))
	var indexedSources int
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM private_asset_reference_index WHERE asset_id=$1`, linkedAsset).Scan(&indexedSources))
	require.Equal(t, 3, indexedSources, "migration indexes issue, comment and historical references")
	var assetTeam string
	require.NoError(t, db.QueryRow(`SELECT team_id::TEXT FROM assets WHERE id=$1`, linkedAsset).Scan(&assetTeam))
	require.Equal(t, fixture.teamA.String(), assetTeam)
	var unattributed int
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM assets WHERE team_id IS NULL`).Scan(&unattributed))
	require.Equal(t, 2, unattributed)
	_, err = db.Exec(`UPDATE teams SET is_private=TRUE WHERE id=$1`, fixture.teamA)
	require.ErrorContains(t, err, "crosses a private-team boundary", "ambiguous legacy attachment prevents privatization")
	_, err = db.Exec(`UPDATE issues SET description=$1 WHERE id=$2`, "/api/workspaces/old/assets/"+linkedAsset.String(), fixture.issueA)
	require.NoError(t, err)
	var source string
	require.NoError(t, db.QueryRow(`SELECT source_team_ids[1]::text FROM notifications WHERE issue_id=$1`, fixture.issueA).Scan(&source))
	require.Equal(t, fixture.teamA.String(), source)

	var safeMode bool
	require.NoError(t, db.QueryRow(`SELECT EXISTS(SELECT 1 FROM workspace_privacy WHERE workspace_id=$1)`, fixture.workspaceA).Scan(&safeMode))
	require.False(t, safeMode, "public-only workspace keeps original realtime")
	var count int
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM teams WHERE NOT is_private`).Scan(&count))
	require.Equal(t, 2, count)
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM issues`).Scan(&count))
	require.Equal(t, 2, count)
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM projects WHERE team_id IS NULL`).Scan(&count))
	require.Equal(t, 1, count)
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM team_members`).Scan(&count))
	require.Equal(t, 1, count)
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM github_installations`).Scan(&count))
	require.Equal(t, 2, count)
	_, err = db.Exec(`UPDATE teams SET is_private=NULL WHERE id=$1`, fixture.teamA)
	require.Error(t, err, "visibility cannot be unknown")
	_, err = db.Exec(`INSERT INTO project_status_visibility(project_id,status_id) SELECT p.id,i.status_id FROM projects p JOIN issues i ON i.id=$2 WHERE p.workspace_id=$1 AND p.team_id IS NULL`, fixture.workspaceA, fixture.issueA)
	require.NoError(t, err)
	_, err = db.Exec(`UPDATE teams SET is_private=TRUE WHERE id=$1`, fixture.teamA)
	require.ErrorContains(t, err, "crosses a private-team boundary", "legacy public project/status associations must block privatization")
	_, err = db.Exec(`DELETE FROM project_status_visibility WHERE project_id IN (SELECT id FROM projects WHERE workspace_id=$1 AND team_id IS NULL)`, fixture.workspaceA)
	require.NoError(t, err)
	// A formerly public team may contain cross-team/teamless references.
	// Privatization must fail atomically until those references are resolved.
	_, err = db.Exec(`UPDATE issues SET project_id=(SELECT id FROM projects WHERE workspace_id=$1 AND team_id IS NULL LIMIT 1) WHERE id=$2`, fixture.workspaceA, fixture.issueA)
	require.NoError(t, err)
	_, err = db.Exec(`UPDATE teams SET is_private=TRUE WHERE id=$1`, fixture.teamA)
	require.ErrorContains(t, err, "crosses a private-team boundary")
	_, err = db.Exec(`UPDATE issues SET project_id=$1 WHERE id=$2`, fixture.projectA, fixture.issueA)
	require.NoError(t, err)
	_, err = db.Exec(`UPDATE teams SET is_private=TRUE WHERE id=$1`, fixture.teamA)
	require.NoError(t, err)
	_, err = db.Exec(`UPDATE projects SET team_id=NULL WHERE id=$1`, fixture.projectA)
	require.ErrorContains(t, err, "Moving resources across a private-team boundary")
	_, err = db.Exec(`DELETE FROM teams WHERE id=$1`, fixture.teamA)
	require.ErrorContains(t, err, "Delete private projects and templates")
	boundaryDown, err := os.ReadFile("000040_private_team_boundaries.down.sql")
	require.NoError(t, err)
	boundaryTx, err := db.Begin()
	require.NoError(t, err)
	_, err = boundaryTx.Exec(string(boundaryDown))
	require.ErrorContains(t, err, "Cannot remove private-team protection")
	require.NoError(t, boundaryTx.Rollback())
	var legacyCount int
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM notifications WHERE workspace_id=$1 AND issue_id IS NULL`, fixture.workspaceA).Scan(&legacyCount))
	require.Zero(t, legacyCount, "unattributable legacy titles must not survive privatization")
	notificationDown, err := os.ReadFile("000041_notification_privacy.down.sql")
	require.NoError(t, err)
	notificationTx, err := db.Begin()
	require.NoError(t, err)
	_, err = notificationTx.Exec(string(notificationDown))
	require.ErrorContains(t, err, "Cannot remove private-team protection")
	require.NoError(t, notificationTx.Rollback())
	require.NoError(t, db.QueryRow(`SELECT EXISTS(SELECT 1 FROM workspace_privacy WHERE workspace_id=$1)`, fixture.workspaceA).Scan(&safeMode))
	require.True(t, safeMode)
	realtimeDown, err := os.ReadFile("000042_private_realtime.down.sql")
	require.NoError(t, err)
	realtimeTx, err := db.Begin()
	require.NoError(t, err)
	_, err = realtimeTx.Exec(string(realtimeDown))
	require.ErrorContains(t, err, "Cannot remove private-team protection")
	require.NoError(t, realtimeTx.Rollback())
	concurrencyDown, err := os.ReadFile("000046_private_guard_concurrency.down.sql")
	require.NoError(t, err)
	concurrencyTx, err := db.Begin()
	require.NoError(t, err)
	_, err = concurrencyTx.Exec(string(concurrencyDown))
	require.ErrorContains(t, err, "Cannot remove private-team protection")
	require.NoError(t, concurrencyTx.Rollback())
	projectStatusDown, err := os.ReadFile("000045_private_project_statuses.down.sql")
	require.NoError(t, err)
	projectStatusTx, err := db.Begin()
	require.NoError(t, err)
	_, err = projectStatusTx.Exec(string(projectStatusDown))
	require.ErrorContains(t, err, "Cannot remove private-team protection")
	require.NoError(t, projectStatusTx.Rollback())
	externalDown, err := os.ReadFile("000044_private_external_paths.down.sql")
	require.NoError(t, err)
	externalTx, err := db.Begin()
	require.NoError(t, err)
	_, err = externalTx.Exec(string(externalDown))
	require.ErrorContains(t, err, "Cannot remove private-team protection")
	require.NoError(t, externalTx.Rollback())
	assetDown, err := os.ReadFile("000043_asset_privacy.down.sql")
	require.NoError(t, err)
	assetTx, err := db.Begin()
	require.NoError(t, err)
	_, err = assetTx.Exec(string(assetDown))
	require.ErrorContains(t, err, "Cannot remove private-team protection")
	require.NoError(t, assetTx.Rollback())
	// Execute the actual down SQL inside a transaction. Its expected error must
	// roll back without changing the migrated schema or any private data.
	down, err := os.ReadFile("000039_private_teams.down.sql")
	require.NoError(t, err)
	tx, err := db.Begin()
	require.NoError(t, err)
	_, err = tx.Exec(string(down))
	require.ErrorContains(t, err, "Cannot remove private-team protection")
	require.NoError(t, tx.Rollback())
	var private bool
	require.NoError(t, db.QueryRow(`SELECT is_private FROM teams WHERE id=$1`, fixture.teamA).Scan(&private))
	require.True(t, private)
	_, err = db.Exec(`UPDATE teams SET is_private=FALSE WHERE id=$1`, fixture.teamA)
	require.NoError(t, err)
	require.NoError(t, db.QueryRow(`SELECT EXISTS(SELECT 1 FROM workspace_privacy WHERE workspace_id=$1)`, fixture.workspaceA).Scan(&safeMode))
	require.True(t, safeMode, "declassification must not release queued private payloads")
	requireConcurrentPrivateBoundary(t, db, fixture)
	quarantineTx, err := db.Begin()
	require.NoError(t, err)
	_, err = quarantineTx.Exec(string(assetDown))
	require.ErrorContains(t, err, "Cannot expose quarantined legacy attachments")
	require.NoError(t, quarantineTx.Rollback())
	_, err = db.Exec(`DELETE FROM assets WHERE team_id IS NULL`)
	require.NoError(t, err)
	require.NoError(t, m.Steps(-8))
	requireMigrationVersion(t, m, 38)
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM issues`).Scan(&count))
	require.Equal(t, 2, count)
	require.NoError(t, m.Steps(8))
	requireMigrationVersion(t, m, 46)
}

// The second statement starts against the public state and waits for the
// workspace lock. Its AFTER guard must see the committed privacy transition.
func requireConcurrentPrivateBoundary(t *testing.T, db *sql.DB, fixture baseMigrationFixture) {
	t.Helper()
	team, status, issue := uuid.New(), uuid.New(), uuid.New()
	_, err := db.Exec(`INSERT INTO teams(id,workspace_id,name,key) VALUES($1,$2,'Concurrent','CONCUR')`, team, fixture.workspaceA)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO team_statuses(id,team_id,name,slug,category) VALUES($1,$2,'Todo','todo','unstarted')`, status, team)
	require.NoError(t, err)
	_, err = db.Exec(`INSERT INTO issues(id,workspace_id,team_id,number,identifier_text,title,creator_id,status_id) VALUES($1,$2,$3,1,'CONCUR-1','Concurrent',$4,$5)`, issue, fixture.workspaceA, team, fixture.userA, status)
	require.NoError(t, err)
	transition, err := db.Begin()
	require.NoError(t, err)
	defer func() { _ = transition.Rollback() }()
	_, err = transition.Exec(`UPDATE teams SET is_private=TRUE WHERE id=$1`, fixture.teamA)
	require.NoError(t, err)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	writer, err := db.BeginTx(ctx, nil)
	require.NoError(t, err)
	defer func() { _ = writer.Rollback() }()
	marker := "privacy-race-" + uuid.NewString()
	_, err = writer.ExecContext(ctx, `SELECT set_config('application_name',$1,true)`, marker)
	require.NoError(t, err)
	result := make(chan error, 1)
	go func() {
		_, err := writer.ExecContext(ctx, `UPDATE issues SET parent_id=$1 WHERE id=$2`, fixture.issueA, issue)
		result <- err
	}()
	require.Eventually(t, func() bool {
		var blocked bool
		err := db.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE application_name=$1 AND wait_event_type='Lock')`, marker).Scan(&blocked)
		return err == nil && blocked
	}, 5*time.Second, 20*time.Millisecond, "relationship writer must wait for the privacy transaction")
	require.NoError(t, transition.Commit())
	require.ErrorContains(t, <-result, "crosses a private-team boundary")
	require.NoError(t, writer.Rollback())
	var parent sql.NullString
	require.NoError(t, db.QueryRow(`SELECT parent_id FROM issues WHERE id=$1`, issue).Scan(&parent))
	require.False(t, parent.Valid)
	_, err = db.Exec(`UPDATE teams SET is_private=FALSE WHERE id=$1`, fixture.teamA)
	require.NoError(t, err)
	_, err = db.Exec(`DELETE FROM teams WHERE id=$1`, team)
	require.NoError(t, err)
}
